const hola = {
  Architecture: "x86_64",
  CreationDate: "2023-08-10T05:36:56.000Z",
  ImageId: "ami-09301a37d119fe4c5",
  ImageLocation: "amazon/Windows_Server-2022-English-Full-Base-2023.08.10",
  ImageType: "machine",
  Public: true,
  OwnerId: "801119661308",
  Platform: "windows",
  PlatformDetails: "Windows",
  UsageOperation: "RunInstances:0002",
  State: "available",
  BlockDeviceMappings: [
    { DeviceName: "/dev/sda1", Ebs: [Object] },
    { DeviceName: "xvdca", VirtualName: "ephemeral0" },
    { DeviceName: "xvdcb", VirtualName: "ephemeral1" },
    { DeviceName: "xvdcc", VirtualName: "ephemeral2" },
    { DeviceName: "xvdcd", VirtualName: "ephemeral3" },
    { DeviceName: "xvdce", VirtualName: "ephemeral4" },
    { DeviceName: "xvdcf", VirtualName: "ephemeral5" },
    { DeviceName: "xvdcg", VirtualName: "ephemeral6" },
    { DeviceName: "xvdch", VirtualName: "ephemeral7" },
    { DeviceName: "xvdci", VirtualName: "ephemeral8" },
    { DeviceName: "xvdcj", VirtualName: "ephemeral9" },
    { DeviceName: "xvdck", VirtualName: "ephemeral10" },
    { DeviceName: "xvdcl", VirtualName: "ephemeral11" },
    { DeviceName: "xvdcm", VirtualName: "ephemeral12" },
    { DeviceName: "xvdcn", VirtualName: "ephemeral13" },
    { DeviceName: "xvdco", VirtualName: "ephemeral14" },
    { DeviceName: "xvdcp", VirtualName: "ephemeral15" },
    { DeviceName: "xvdcq", VirtualName: "ephemeral16" },
    { DeviceName: "xvdcr", VirtualName: "ephemeral17" },
    { DeviceName: "xvdcs", VirtualName: "ephemeral18" },
    { DeviceName: "xvdct", VirtualName: "ephemeral19" },
    { DeviceName: "xvdcu", VirtualName: "ephemeral20" },
    { DeviceName: "xvdcv", VirtualName: "ephemeral21" },
    { DeviceName: "xvdcw", VirtualName: "ephemeral22" },
    { DeviceName: "xvdcx", VirtualName: "ephemeral23" },
    { DeviceName: "xvdcy", VirtualName: "ephemeral24" },
    { DeviceName: "xvdcz", VirtualName: "ephemeral25" },
  ],
  Description:
    "Microsoft Windows Server 2022 Full Locale English AMI provided by Amazon",
  EnaSupport: true,
  Hypervisor: "xen",
  ImageOwnerAlias: "amazon",
  Name: "Windows_Server-2022-English-Full-Base-2023.08.10",
  RootDeviceName: "/dev/sda1",
  RootDeviceType: "ebs",
  SriovNetSupport: "simple",
  VirtualizationType: "hvm",
  DeprecationTime: "2025-08-10T05:36:56.000Z",
};

const efe = {
  Architecture: "x86_64",
  CreationDate: "2023-08-10T09:12:40.000Z",
  ImageId: "ami-0e4e4616758377319",
  ImageLocation:
    "amazon/Windows_Server-2019-English-Full-SQL_2019_Enterprise-2023.08.10",
  ImageType: "machine",
  Public: true,
  OwnerId: "801119661308",
  Platform: "windows",
  PlatformDetails: "Windows with SQL Server Enterprise",
  UsageOperation: "RunInstances:0102",
  State: "available",
  BlockDeviceMappings: [
    { DeviceName: "/dev/sda1", Ebs: [Object] },
    { DeviceName: "xvdca", VirtualName: "ephemeral0" },
    { DeviceName: "xvdcb", VirtualName: "ephemeral1" },
    { DeviceName: "xvdcc", VirtualName: "ephemeral2" },
    { DeviceName: "xvdcd", VirtualName: "ephemeral3" },
    { DeviceName: "xvdce", VirtualName: "ephemeral4" },
    { DeviceName: "xvdcf", VirtualName: "ephemeral5" },
    { DeviceName: "xvdcg", VirtualName: "ephemeral6" },
    { DeviceName: "xvdch", VirtualName: "ephemeral7" },
    { DeviceName: "xvdci", VirtualName: "ephemeral8" },
    { DeviceName: "xvdcj", VirtualName: "ephemeral9" },
    { DeviceName: "xvdck", VirtualName: "ephemeral10" },
    { DeviceName: "xvdcl", VirtualName: "ephemeral11" },
    { DeviceName: "xvdcm", VirtualName: "ephemeral12" },
    { DeviceName: "xvdcn", VirtualName: "ephemeral13" },
    { DeviceName: "xvdco", VirtualName: "ephemeral14" },
    { DeviceName: "xvdcp", VirtualName: "ephemeral15" },
    { DeviceName: "xvdcq", VirtualName: "ephemeral16" },
    { DeviceName: "xvdcr", VirtualName: "ephemeral17" },
    { DeviceName: "xvdcs", VirtualName: "ephemeral18" },
    { DeviceName: "xvdct", VirtualName: "ephemeral19" },
    { DeviceName: "xvdcu", VirtualName: "ephemeral20" },
    { DeviceName: "xvdcv", VirtualName: "ephemeral21" },
    { DeviceName: "xvdcw", VirtualName: "ephemeral22" },
    { DeviceName: "xvdcx", VirtualName: "ephemeral23" },
    { DeviceName: "xvdcy", VirtualName: "ephemeral24" },
    { DeviceName: "xvdcz", VirtualName: "ephemeral25" },
  ],
  Description:
    "Microsoft Windows Server 2019 Full Locale English with SQL Enterprise 2019 AMI provided by Amazon",
  EnaSupport: true,
  Hypervisor: "xen",
  ImageOwnerAlias: "amazon",
  Name: "Windows_Server-2019-English-Full-SQL_2019_Enterprise-2023.08.10",
  RootDeviceName: "/dev/sda1",
  RootDeviceType: "ebs",
  SriovNetSupport: "simple",
  VirtualizationType: "hvm",
  DeprecationTime: "2025-08-10T09:12:40.000Z",
};
